multiple/config/routes.rb
Multiple::Application.routes.draw do
  resources :categories

  resources :items

  root :to => 'home#index'

end

multiple/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  
  has_many :category_items, :dependent => :destroy
  has_many :items, :through => :category_items
end

multiple/app/models/category_item.rb
class CategoryItem < ActiveRecord::Base
  belongs_to :category
  belongs_to :item
end

multiple/app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :detail, :name, :category_ids
  validates :name, :presence => :true
  
  has_many :category_items, :dependent => :destroy
  has_many :categories, :through => :category_items
end

multiple/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

multiple/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

multiple/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

multiple/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

multiple/app/helpers/application_helper.rb
module ApplicationHelper
  def br(s)
    s && h(s).gsub(/(\r\n?)|(\n)/, '<br />').html_safe
  end
  
  def rbr(s)
    s && s.gsub(/(\r\n?)|(\n)/, '<br />').html_safe
  end
end

multiple/app/helpers/categories_helper.rb
module CategoriesHelper
end

multiple/app/helpers/home_helper.rb
module HomeHelper
end

multiple/app/helpers/items_helper.rb
module ItemsHelper
end

multiple/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

multiple/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

multiple/app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

multiple/app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

multiple/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
	<b>Items:</b>
	<ul>
	<% @category.items.each do |i| %>
		<li><%= i.name %></li>
	<% end %>
	</ul>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

multiple/app/views/home/index.html.erb
<h1>Multiple-against-multiple Sample</h1>
<h2>Welcome!</h2>
<h2>What I did</h2>
<ul>
	<li>
		Multiple-against-multiple relation: Items and Categories are linked with multiple-against-multiple relation<br />
		In items#show you can see categories related to an item, and in categories#show you can see items that belongs to a certain category<br />
		Categories for items can be set with a multiple select form
	</li>
	<li>And subfeatures</li>
	<ul>
		<li>
			In ApplicationHelper wrote line-break helper(br) and line-break helper without html escape(rbr)<br />
			(use with care because it might cause cross-site-scripting)
		</li>
		<li>
			Set root controller method(as usual)
		</li>
	</ul>
</ul>

multiple/app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :detail %><br />
    <%= f.text_area :detail %>
  </div>
  <div class="field">
	  <%= f.label :categories %><br />
	  <%= f.select :category_ids, Category.all.collect {|x| [x.name, x.id]}, {}, :multiple => true, :size => 5 %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

multiple/app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

multiple/app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

multiple/app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

multiple/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Detail:</b>
  <%=br @item.detail %>
</p>

<p>
	<b>Categories:</b>
	<ul>
		<% @item.categories.each do |cat| %>
		<li><%= cat.name %></li>
		<% end %>
	</ul>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

multiple/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Multiple</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<p>
<%= link_to "Items", items_path %> / <%= link_to "Categories", categories_path %> / <%= link_to "Root", root_path %>
</p>

</body>
</html>